- id: curlylint
  name: curlylint
  description: A linter which checks the indentation and the correctness of Jinja-like/HTML templates.
  language: python
  language_version: python3
  entry: curlylint
  types: [jinja]
