- id: jinjalint
  name: jinjalint
  description: A linter which checks the indentation and the correctness of Jinja-like/HTML templates.
  language: python
  language_version: python3
  entry: jinjalint
  types: [jinja]
