[tool.curlylint]
# Specify additional Jinja elements which can wrap HTML here. You
# don’t neet to specify simple elements which can't wrap anything like
# {% extends %} or {% include %}.
template_tags = [
  ["of", "elseof", "endof"],
  ["cache", "endcache"],
  ["captureas", "endcaptureas"]
]

[tool.curlylint.rules]
# How many spaces
indent = 4
